import type { TriggerQueueCapability } from "./types.js";

const capability = (value: TriggerQueueCapability): TriggerQueueCapability =>
  value;

export const genericEventReactionTriggerTypes = [
  "lifeRemoved",
  "damageDealt",
  "fieldRemoved",
  "cardDrawn",
  "cardPlayed",
  "cardRested",
  "donReturned",
  "donAttached",
  "attackDeclared",
  "endOfBattle",
  "onBlock",
  "effectQueued",
  "effectResolved",
  "triggerActivated",
] as const;

export const genericEventReactionCapabilities = [
  capability({
    triggerType: "lifeRemoved",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["cardMoved"],
    behaviorProbeScenario: { kind: "lifeRemoved", category: "character" },
  }),
  capability({
    triggerType: "damageDealt",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["damageDealt"],
    behaviorProbeScenario: { kind: "damageDealt", category: "character" },
  }),
  capability({
    triggerType: "fieldRemoved",
    category: "auto",
    sourcePresencePolicies: [
      "mustRemainInSameZone",
      "resolveFromLastKnownInformation",
    ],
    router: "genericEventReaction",
    runtimeEventTypes: ["cardMoved"],
    behaviorProbeScenario: { kind: "fieldRemoved", category: "character" },
  }),
  capability({
    triggerType: "cardDrawn",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["cardDrawn"],
    behaviorProbeScenario: { kind: "cardDrawn", category: "character" },
  }),
  capability({
    triggerType: "cardPlayed",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["cardPlayed"],
    behaviorProbeScenario: { kind: "cardPlayed", category: "character" },
  }),
  capability({
    triggerType: "cardRested",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["cardRested"],
    behaviorProbeScenario: { kind: "cardRested", category: "character" },
  }),
  capability({
    triggerType: "donReturned",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["donReturned"],
    behaviorProbeScenario: { kind: "donReturned", category: "character" },
  }),
  capability({
    triggerType: "donAttached",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["donAttached"],
    behaviorProbeScenario: { kind: "donAttached", category: "character" },
  }),
  capability({
    triggerType: "attackDeclared",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["attackDeclared"],
    behaviorProbeScenario: { kind: "attackDeclared", category: "leader" },
  }),
  capability({
    triggerType: "endOfBattle",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["battleEnded"],
    behaviorProbeScenario: { kind: "endOfBattle", category: "character" },
  }),
  capability({
    triggerType: "onBlock",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["blockerActivated"],
    behaviorProbeScenario: { kind: "onBlock", category: "character" },
  }),
  capability({
    triggerType: "effectQueued",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["effectQueued"],
    behaviorProbeScenario: { kind: "effectQueued", category: "character" },
  }),
  capability({
    triggerType: "effectResolved",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["effectResolved"],
  }),
  capability({
    triggerType: "triggerActivated",
    category: "auto",
    sourcePresencePolicies: ["mustRemainInSameZone"],
    router: "genericEventReaction",
    runtimeEventTypes: ["triggerActivated"],
    behaviorProbeScenario: { kind: "triggerActivated", category: "character" },
  }),
] as const satisfies readonly TriggerQueueCapability[];
