import {
  parseDonFieldCountCondition,
  parseEitherPlayerLifeCountCondition,
  parseFieldCardCountCondition,
  parseHandCountCondition,
  parseLeaderColorCountCondition,
  parseLeaderNameCondition,
  parseLifeCountCondition,
  parseNoOtherNamedCharactersCondition,
  parseOnlyMatchingFieldCardsCondition,
  parseOpponentRestedCharactersCondition,
  parseRestedCardCountCondition,
  parseSelfFieldCountCondition,
  parseTrashCountCondition,
  parseTurnCountCondition,
} from "../conditions/index.js";
import {
  parseActivateReferencedEffectInstruction,
  parseActivateSelectedEventInstruction,
  parseAddActiveDonFromDonDeckInstruction,
  parseAddFromTrashToHandInstruction,
  parseAddRestedDonFromDonDeckInstruction,
  parseAttachRestedDonInstruction,
  parseBasePowerBecomeInstruction,
  parseContinuousFieldModifyCostInstruction,
  parseDamageInstruction,
  parseDrawInstruction,
  parseExplicitProtectionInstruction,
  parseHandCounterSetInstruction,
  parseHandToDeckBottomInstruction,
  parseInvalidateEffectsInstruction,
  parseKoInstruction,
  parseLifeMovementInstruction,
  parseModifyCostInstruction,
  parseModifyPowerInstruction,
  parseOpponentEffectFieldRemovalProtectionInstruction,
  parsePlaceAtOwnerDeckBottomInstruction,
  parsePlayFromHandInstruction,
  parsePlayFromTrashInstruction,
  parsePlaySourceInstruction,
  parsePreventDonActivationInstruction,
  parsePreventDrawInstruction,
  parsePreventOpponentCharactersAttackInstruction,
  parsePreventOpponentCharactersRefreshInstruction,
  parsePreventPlayInstruction,
  parsePreventThatCharacterRefreshInstruction,
  parseRestOpponentCharactersInstruction,
  parseRestOpponentCharactersOrDonCardsInstruction,
  parseRestOpponentLeaderOrCharactersInstruction,
  parseReturnToOwnerHandInstruction,
  parseRevealTopInstruction,
  parseSelectFromTrashChoiceInstruction,
  parseSelfCannotAttackInstruction,
  parseSelfHandModifyCostInstruction,
  parseSetBasePowerInstruction,
  parseSetDonActiveInstruction,
  parseSetFieldActiveInstruction,
  parseTargetedKeywordGrantInstruction,
  parseTargetedModifyCostInstruction,
  parseThisCharacterKeywordGrantInstruction,
  parseTopDeckPlacementInstruction,
  parseTrashFromDeckTopInstruction,
  parseTrashFromHandInstruction,
  parseTrashInstruction,
  parseWinGameInstruction,
  parseYourLeaderConditionalPowerInstruction,
  parseYourLeaderPowerOpponentNextEndInstruction,
} from "../instructions/index.js";
import {
  parseExplicitActionBasePowerInstruction,
  parseExplicitActionKeywordGrantInstruction,
} from "./explicit-action.js";

export const instructionParsers = [
  parseDrawInstruction,
  parseDamageInstruction,
  parseActivateReferencedEffectInstruction,
  parseActivateSelectedEventInstruction,
  parseAddFromTrashToHandInstruction,
  parseAddActiveDonFromDonDeckInstruction,
  parseAddRestedDonFromDonDeckInstruction,
  parseAttachRestedDonInstruction,
  parseSetFieldActiveInstruction,
  parseSetDonActiveInstruction,
  parseInvalidateEffectsInstruction,
  parseTrashFromHandInstruction,
  parseTrashFromDeckTopInstruction,
  parseLifeMovementInstruction,
  parseHandToDeckBottomInstruction,
  parseTopDeckPlacementInstruction,
  parseTrashInstruction,
  parsePlayFromHandInstruction,
  parseSelectFromTrashChoiceInstruction,
  parsePlayFromTrashInstruction,
  parsePlaySourceInstruction,
  parsePreventDrawInstruction,
  parsePreventDonActivationInstruction,
  parsePreventPlayInstruction,
  parseRevealTopInstruction,
  parseExplicitProtectionInstruction,
  parseModifyPowerInstruction,
  parseTargetedKeywordGrantInstruction,
  parseTargetedModifyCostInstruction,
  parseModifyCostInstruction,
  parseKoInstruction,
  parsePlaceAtOwnerDeckBottomInstruction,
  parseReturnToOwnerHandInstruction,
  parseRestOpponentLeaderOrCharactersInstruction,
  parseRestOpponentCharactersOrDonCardsInstruction,
  parseRestOpponentCharactersInstruction,
  parsePreventOpponentCharactersAttackInstruction,
  parsePreventOpponentCharactersRefreshInstruction,
  parsePreventThatCharacterRefreshInstruction,
  parseWinGameInstruction,
  parseYourLeaderPowerOpponentNextEndInstruction,
  parseExplicitActionKeywordGrantInstruction,
  parseExplicitActionBasePowerInstruction,
] as const;

export const conditionParsers = [
  parseDonFieldCountCondition,
  parseHandCountCondition,
  parseOpponentRestedCharactersCondition,
  parseRestedCardCountCondition,
  parseSelfFieldCountCondition,
  parseTrashCountCondition,
  parseEitherPlayerLifeCountCondition,
  parseLifeCountCondition,
  parseLeaderColorCountCondition,
  parseLeaderNameCondition,
  parseFieldCardCountCondition,
  parseNoOtherNamedCharactersCondition,
  parseOnlyMatchingFieldCardsCondition,
  parseTurnCountCondition,
] as const;

export const continuousInstructionParsers = [
  parseOpponentEffectFieldRemovalProtectionInstruction,
  parseThisCharacterKeywordGrantInstruction,
  parseSelfCannotAttackInstruction,
  parseYourLeaderConditionalPowerInstruction,
  parseSetBasePowerInstruction,
  parseBasePowerBecomeInstruction,
  parseHandCounterSetInstruction,
  parseContinuousFieldModifyCostInstruction,
  parseSelfHandModifyCostInstruction,
] as const;
