export type {
  Action,
  BaseDecision,
  CardSelectionCandidate,
  ChooseEffectOptionDecision,
  ChooseOptionalActivationDecision,
  ChooseReplacementDecision,
  ChooseTriggerOrderDecision,
  ConfirmLifeTriggerDecision,
  DecisionResponse,
  DeclareLoopCountDecision,
  LegalAction,
  MulliganDecision,
  OrderCardsDecision,
  PayCostDecision,
  PaymentOption,
  PaymentSpec,
  PendingDecision,
  RollbackConsentDecision,
  SelectCardsDecision,
  SelectTargetsDecision,
  TargetCandidate,
} from "./canonical.js";
