import { expect, test } from "vitest";
import { EXPORT_OWNERSHIP_MANIFEST } from "./export-ownership.manifest.js";

const canonicalModuleFiles = [
  "types/primitives.ts",
  "types/card-metadata.ts",
  "types/events.ts",
  "types/view.ts",
  "types/game-state.ts",
  "types/effects.ts",
  "types/decisions.ts",
  "types/runtime.ts",
];

async function readCanonicalModuleSources(): Promise<string[]> {
  const { readFile } = await import("node:fs/promises");

  return Promise.all(
    canonicalModuleFiles.map((fileName) =>
      readFile(new URL(`../../../contracts/${fileName}`, import.meta.url), {
        encoding: "utf8",
      }),
    ),
  );
}

import type {
  Action as PackageAction,
  AtomicMutation as PackageAtomicMutation,
  Attribute as PackageAttribute,
  AuditEntry as PackageAuditEntry,
  BanlistRecord as PackageBanlistRecord,
  BaseDecision as PackageBaseDecision,
  BattleState as PackageBattleState,
  BattleStep as PackageBattleStep,
  Brand as PackageBrand,
  CardCategory as PackageCardCategory,
  CardColor as PackageCardColor,
  Cardinality as PackageCardinality,
  CardFilter as PackageCardFilter,
  CardId as PackageCardId,
  CardImplementationRecord as PackageCardImplementationRecord,
  CardInstance as PackageCardInstance,
  CardMetadata as PackageCardMetadata,
  CardRef as PackageCardRef,
  CardSelectionCandidate as PackageCardSelectionCandidate,
  CardSelectionRequest as PackageCardSelectionRequest,
  CardSnapshot as PackageCardSnapshot,
  CardSupportStatus as PackageCardSupportStatus,
  CardVariant as PackageCardVariant,
  CausalityRef as PackageCausalityRef,
  ChooseEffectOptionDecision as PackageChooseEffectOptionDecision,
  ChooseOptionalActivationDecision as PackageChooseOptionalActivationDecision,
  ChooseQuantityDecision as PackageChooseQuantityDecision,
  ChooseQuantityResponse as PackageChooseQuantityResponse,
  ChooseReplacementDecision as PackageChooseReplacementDecision,
  ChooseTriggerOrderDecision as PackageChooseTriggerOrderDecision,
  Comparator as PackageComparator,
  ComputedCardView as PackageComputedCardView,
  ComputedGameView as PackageComputedGameView,
  Condition as PackageCondition,
  ConfirmLifeTriggerDecision as PackageConfirmLifeTriggerDecision,
  ContinuousEffect as PackageContinuousEffect,
  ContinuousEffectRecord as PackageContinuousEffectRecord,
  Cost as PackageCost,
  CustomHandler as PackageCustomHandler,
  DecisionId as PackageDecisionId,
  DecisionResponse as PackageDecisionResponse,
  DeckValidationError as PackageDeckValidationError,
  DeckValidationResult as PackageDeckValidationResult,
  DeckValidationWarning as PackageDeckValidationWarning,
  DecklistEntry as PackageDecklistEntry,
  DeclareLoopCountDecision as PackageDeclareLoopCountDecision,
  DeferredTriggerBucket as PackageDeferredTriggerBucket,
  Duration as PackageDuration,
  Effect as PackageEffect,
  EffectBlock as PackageEffectBlock,
  EffectCategory as PackageEffectCategory,
  EffectContext as PackageEffectContext,
  EffectDefinition as PackageEffectDefinition,
  EffectDefinitionMetadata as PackageEffectDefinitionMetadata,
  EffectDslFieldRemovalProtection as PackageEffectDslFieldRemovalProtection,
  EffectExecutionFrame as PackageEffectExecutionFrame,
  EffectExecutionContext as PackageEffectExecutionContext,
  EffectExecutionPendingDecisionContinuation as PackageEffectExecutionPendingDecisionContinuation,
  EffectId as PackageEffectId,
  EffectOption as PackageEffectOption,
  EffectQueueEntry as PackageEffectQueueEntry,
  EngineError as PackageEngineError,
  EngineEvent as PackageEngineEvent,
  EngineEventId as PackageEngineEventId,
  EngineEventType as PackageEngineEventType,
  EngineResult as PackageEngineResult,
  EngineStepResult as PackageEngineStepResult,
  EventVisibility as PackageEventVisibility,
  ExactCardinality as PackageExactCardinality,
  ExactCardTargetSpec as PackageExactCardTargetSpec,
  ExactQuantityDecision as PackageExactQuantityDecision,
  FailurePolicy as PackageFailurePolicy,
  FieldRemovalProtection as PackageFieldRemovalProtection,
  GameState as PackageGameState,
  HandSelectCardsEffect as PackageHandSelectCardsEffect,
  HandSelectionId as PackageHandSelectionId,
  InstanceId as PackageInstanceId,
  Keyword as PackageKeyword,
  LegalAction as PackageLegalAction,
  LifeCard as PackageLifeCard,
  Loadout as PackageLoadout,
  LoadoutId as PackageLoadoutId,
  LoopSignature as PackageLoopSignature,
  MatchCardManifest as PackageMatchCardManifest,
  MatchId as PackageMatchId,
  MatchSource as PackageMatchSource,
  MatchStatus as PackageMatchStatus,
  Modifier as PackageModifier,
  ModifierLayer as PackageModifierLayer,
  ModifierOperation as PackageModifierOperation,
  MulliganDecision as PackageMulliganDecision,
  MultiZoneTargetRequest as PackageMultiZoneTargetRequest,
  NormalizedErrata as PackageNormalizedErrata,
  OncePerTurnRecord as PackageOncePerTurnRecord,
  OptionalCost as PackageOptionalCost,
  OptionalCostSegmentResult as PackageOptionalCostSegmentResult,
  OptionalPayCostDecision as PackageOptionalPayCostDecision,
  OrderCardsDecision as PackageOrderCardsDecision,
  PaymentOption as PackagePaymentOption,
  PaymentDeclinedResponse as PackagePaymentDeclinedResponse,
  PaymentResponse as PackagePaymentResponse,
  PaymentSpec as PackagePaymentSpec,
  PayCostEffect as PackagePayCostEffect,
  PlayHandSelectedEffect as PackagePlayHandSelectedEffect,
  PlaySelectedEffect as PackagePlaySelectedEffect,
  PayCostDecision as PackagePayCostDecision,
  PendingDecision as PackagePendingDecision,
  PlayerGameTimer as PackagePlayerGameTimer,
  PlayerId as PackagePlayerId,
  PlayerRef as PackagePlayerRef,
  PlayerState as PackagePlayerState,
  PoneglyphCardDetail as PackagePoneglyphCardDetail,
  PoneglyphErrata as PackagePoneglyphErrata,
  PoneglyphLegalityRecord as PackagePoneglyphLegalityRecord,
  PoneglyphOfficialFaq as PackagePoneglyphOfficialFaq,
  PoneglyphVariant as PackagePoneglyphVariant,
  Protection as PackageProtection,
  ProtectionExclusionPolicy as PackageProtectionExclusionPolicy,
  ProtectionFieldRemovalClassification as PackageProtectionFieldRemovalClassification,
  ProtectionFieldRemovalExclusions as PackageProtectionFieldRemovalExclusions,
  ProtectionFieldRemovalMetadata as PackageProtectionFieldRemovalMetadata,
  ProtectionFieldRemovalProcessFamily as PackageProtectionFieldRemovalProcessFamily,
  ProtectionFieldRemovalSourceControllerRelation as PackageProtectionFieldRemovalSourceControllerRelation,
  ProtectionFieldRemovalSourceKind as PackageProtectionFieldRemovalSourceKind,
  ProtectionFieldRemovalTargetScope as PackageProtectionFieldRemovalTargetScope,
  OpponentVisibleState as PackageOpponentVisibleState,
  PlayerView as PackagePlayerView,
  PublicBattleState as PackagePublicBattleState,
  PublicCardView as PackagePublicCardView,
  PublicChooseQuantityDecision as PackagePublicChooseQuantityDecision,
  PublicDecision as PackagePublicDecision,
  PublicLegalAction as PackagePublicLegalAction,
  PublicLifeView as PackagePublicLifeView,
  PublicPendingDecision as PackagePublicPendingDecision,
  PublicRevealRecord as PackagePublicRevealRecord,
  PublicTimerState as PackagePublicTimerState,
  PublicTurnState as PackagePublicTurnState,
  QueueEntryId as PackageQueueEntryId,
  ReplaceableProcessType as PackageReplaceableProcessType,
  ReplacementProcess as PackageReplacementProcess,
  ReplacementProcessState as PackageReplacementProcessState,
  ReplacementTrigger as PackageReplacementTrigger,
  ResolvedCard as PackageResolvedCard,
  ResolvedCardOverlay as PackageResolvedCardOverlay,
  ResolvedCardVariant as PackageResolvedCardVariant,
  ResolvedDeckCard as PackageResolvedDeckCard,
  RevealRecord as PackageRevealRecord,
  RestrictionIndex as PackageRestrictionIndex,
  RngDrawResult as PackageRngDrawResult,
  RngState as PackageRngState,
  RollbackConsentDecision as PackageRollbackConsentDecision,
  RulingNote as PackageRulingNote,
  RuntimeVersionSet as PackageRuntimeVersionSet,
  SavedFieldObjectReference as PackageSavedFieldObjectReference,
  SavedFieldObjectReferenceFailure as PackageSavedFieldObjectReferenceFailure,
  SavedFieldObjectReferenceFailureReason as PackageSavedFieldObjectReferenceFailureReason,
  SavedFieldObjectReferenceFamily as PackageSavedFieldObjectReferenceFamily,
  SavedFieldObjectZone as PackageSavedFieldObjectZone,
  SavedFieldObjectTarget as PackageSavedFieldObjectTarget,
  SavedFieldObjectTargetBinding as PackageSavedFieldObjectTargetBinding,
  SavedPaidCostReference as PackageSavedPaidCostReference,
  SavedProducedObjectsReference as PackageSavedProducedObjectsReference,
  SavedSelectedCardsReference as PackageSavedSelectedCardsReference,
  SavedSelectedTargetsReference as PackageSavedSelectedTargetsReference,
  SearchRequest as PackageSearchRequest,
  SelectCardsDecision as PackageSelectCardsDecision,
  SelectCardsEffect as PackageSelectCardsEffect,
  SelectionId as PackageSelectionId,
  SelectionSetId as PackageSelectionSetId,
  SelectTargetsDecision as PackageSelectTargetsDecision,
  SequenceSavedResultReference as PackageSequenceSavedResultReference,
  SequenceSavedResultReferenceMap as PackageSequenceSavedResultReferenceMap,
  SequenceSegmentResult as PackageSequenceSegmentResult,
  SequenceSegmentResultMap as PackageSequenceSegmentResultMap,
  SequencedEffect as PackageSequencedEffect,
  SimpleProtection as PackageSimpleProtection,
  SourcePresencePolicy as PackageSourcePresencePolicy,
  SetupContinuationState as PackageSetupContinuationState,
  StateHashInput as PackageStateHashInput,
  StateSeq as PackageStateSeq,
  SpectatorEvent as PackageSpectatorEvent,
  SpectatorPolicy as PackageSpectatorPolicy,
  SpectatorRevealRecord as PackageSpectatorRevealRecord,
  SpectatorView as PackageSpectatorView,
  SpectatorVisiblePlayerState as PackageSpectatorVisiblePlayerState,
  Target as PackageTarget,
  TargetCandidate as PackageTargetCandidate,
  TargetPlayerRef as PackageTargetPlayerRef,
  TargetRequest as PackageTargetRequest,
  TargetSpec as PackageTargetSpec,
  TimerState as PackageTimerState,
  TimingWindowId as PackageTimingWindowId,
  TransientCardSet as PackageTransientCardSet,
  Trigger as PackageTrigger,
  TriggerCandidate as PackageTriggerCandidate,
  TurnState as PackageTurnState,
  UpToCardinality as PackageUpToCardinality,
  VariantKey as PackageVariantKey,
  Visibility as PackageVisibility,
  VisiblePlayerState as PackageVisiblePlayerState,
  Winner as PackageWinner,
  Zone as PackageZone,
  ZoneRef as PackageZoneRef,
} from "@optcg/types";

test("TYP-001H ownership manifest keys exactly match canonical export type/interface names", async () => {
  const canonicalSource = (await readCanonicalModuleSources()).join("\n");

  const canonicalNames = [
    ...canonicalSource.matchAll(
      /export\s+(?:type|interface)\s+([A-Za-z0-9_]+)/g,
    ),
  ]
    .map((match) => match[1])
    .sort();
  const manifestNames = Object.keys(EXPORT_OWNERSHIP_MANIFEST).sort();

  expect(manifestNames).toEqual(canonicalNames);
});

test("TYP-001H every manifest-covered canonical export has exactly one valid owner", () => {
  const validOwners = new Set([
    "TYP-001A",
    "TYP-001B",
    "TYP-001C",
    "TYP-001D",
    "TYP-001E",
    "TYP-001F",
    "TYP-001G",
    "TYP-002A",
    "TYP-007A",
    "TYP-007B",
    "TYP-007D",
    "TYP-008A",
    "TYP-009A",
    "TYP-009B",
    "TYP-010",
    "TYP-012A",
    "TYP-012B",
    "SUP-003A",
    "SUP-003I",
  ]);
  for (const owner of Object.values(EXPORT_OWNERSHIP_MANIFEST)) {
    expect(validOwners.has(owner)).toBe(true);
  }
});

test("TYP-001H manifest-covered exports resolve through package-name type imports", () => {
  type PackageNameImportWitness = [
    PackageBrand<string, "PackageNameImportWitness">,
    PackageCardId,
    PackageVariantKey,
    PackageLoadoutId,
    PackageInstanceId,
    PackagePlayerId,
    PackageMatchId,
    PackageEffectId,
    PackageDecisionId,
    PackageEngineEventId,
    PackageQueueEntryId,
    PackageTimingWindowId,
    PackageSelectionSetId,
    PackageSelectionId,
    PackageStateSeq,
    PackageCardCategory,
    PackageCardColor,
    PackageAttribute,
    PackageKeyword,
    PackageZone,
    PackageVisibility,
    PackageComparator,
    PackagePlayerRef,
    PackageBattleStep,
    PackageMatchSource,
    PackageZoneRef,
    PackageCardRef,
    PackageCardSnapshot,
    PackageCardVariant,
    PackageCardMetadata,
    PackageRuntimeVersionSet,
    PackageRulingNote,
    PackageCardSupportStatus,
    PackageCardImplementationRecord,
    PackageBanlistRecord,
    PackageResolvedCardOverlay,
    PackagePoneglyphLegalityRecord,
    PackagePoneglyphOfficialFaq,
    PackagePoneglyphErrata,
    PackagePoneglyphVariant,
    PackagePoneglyphCardDetail,
    PackageNormalizedErrata,
    PackageResolvedCardVariant,
    PackageResolvedCard,
    PackageMatchCardManifest,
    PackageDecklistEntry,
    PackageResolvedDeckCard,
    PackageDeckValidationError,
    PackageDeckValidationWarning,
    PackageDeckValidationResult,
    PackageLoadout,
    PackageEventVisibility,
    PackageEngineEvent,
    PackageEngineEventType,
    PackageCausalityRef,
    PackagePlayerGameTimer,
    PackageTimerState,
    PackagePublicTimerState,
    PackageSequenceSegmentResultMap,
    PackageSequenceSavedResultReferenceMap,
    PackageEffectExecutionPendingDecisionContinuation,
    PackageEffectExecutionFrame,
    PackageRngState,
    PackageRngDrawResult<PackageCardRef>,
    PackageCardInstance,
    PackageLifeCard,
    PackagePlayerState,
    PackageWinner,
    PackageMatchStatus,
    PackageBattleState,
    PackageTurnState,
    PackageSetupContinuationState,
    PackageTargetCandidate,
    PackageCardSelectionCandidate,
    PackageAuditEntry,
    PackageLoopSignature,
    PackageRevealRecord,
    PackageReplacementProcessState,
    PackageDeferredTriggerBucket,
    PackageProtectionFieldRemovalProcessFamily,
    PackageProtectionFieldRemovalClassification,
    PackageProtectionFieldRemovalSourceKind,
    PackageProtectionFieldRemovalSourceControllerRelation,
    PackageProtectionFieldRemovalTargetScope,
    PackageProtectionExclusionPolicy,
    PackageProtectionFieldRemovalExclusions,
    PackageProtectionFieldRemovalMetadata,
    PackageSimpleProtection,
    PackageFieldRemovalProtection,
    PackageProtection,
    PackageOpponentVisibleState,
    PackagePlayerView,
    PackagePublicBattleState,
    PackagePublicCardView,
    PackagePublicChooseQuantityDecision,
    PackagePublicDecision,
    PackagePublicPendingDecision,
    PackagePublicLegalAction,
    PackagePublicLifeView,
    PackagePublicRevealRecord,
    PackageSpectatorRevealRecord,
    PackageSpectatorEvent,
    PackageRestrictionIndex,
    PackageComputedCardView,
    PackageComputedGameView,
    PackageEngineStepResult,
    PackageEngineResult,
    PackageStateHashInput,
    PackageAtomicMutation,
    PackageGameState,
    PackagePublicTurnState,
    PackageSpectatorPolicy,
    PackageSpectatorView,
    PackageSpectatorVisiblePlayerState,
    PackageVisiblePlayerState,
    PackageFailurePolicy,
    PackageSourcePresencePolicy,
    PackageEffectCategory,
    PackageTrigger,
    PackageCondition,
    PackageCost,
    PackageOptionalCost,
    PackageTargetPlayerRef,
    PackageTargetRequest,
    PackageMultiZoneTargetRequest,
    PackageExactCardinality<1>,
    PackageUpToCardinality,
    PackageCardinality,
    PackageCardSelectionRequest,
    PackageTarget,
    PackageCardFilter,
    PackageDuration,
    PackageSearchRequest,
    PackageSequenceSegmentResult,
    PackageOptionalCostSegmentResult,
    PackageSavedFieldObjectReferenceFamily,
    PackageSavedFieldObjectTargetBinding,
    PackageSavedFieldObjectReference,
    PackageSavedFieldObjectReferenceFailureReason,
    PackageSavedFieldObjectReferenceFailure,
    PackageSavedFieldObjectZone,
    PackageSavedFieldObjectTarget,
    PackageSavedSelectedCardsReference,
    PackageSavedSelectedTargetsReference,
    PackageSavedPaidCostReference,
    PackageSavedProducedObjectsReference,
    PackageSequenceSavedResultReference,
    PackageHandSelectionId,
    PackageSelectCardsEffect,
    PackageHandSelectCardsEffect,
    PackagePlaySelectedEffect,
    PackagePlayHandSelectedEffect,
    PackagePayCostEffect,
    PackageEffectDslFieldRemovalProtection,
    PackageReplacementTrigger,
    PackageEffectOption,
    PackageSequencedEffect,
    PackageEffect,
    PackageEffectDefinitionMetadata,
    PackageEffectBlock,
    PackageEffectDefinition,
    PackagePaymentSpec,
    PackagePaymentOption,
    PackagePaymentResponse,
    PackagePaymentDeclinedResponse,
    PackageDecisionResponse,
    PackageBaseDecision,
    PackageChooseTriggerOrderDecision,
    PackageChooseOptionalActivationDecision,
    PackagePayCostDecision,
    PackageOptionalPayCostDecision,
    PackageSelectTargetsDecision,
    PackageSelectCardsDecision,
    PackageChooseEffectOptionDecision,
    PackageConfirmLifeTriggerDecision,
    PackageOrderCardsDecision,
    PackageMulliganDecision,
    PackageDeclareLoopCountDecision,
    PackageRollbackConsentDecision,
    PackageChooseReplacementDecision,
    PackageChooseQuantityResponse,
    PackageChooseQuantityDecision,
    PackageExactQuantityDecision<1>,
    PackagePendingDecision,
    PackageAction,
    PackageLegalAction,
    PackageOncePerTurnRecord,
    PackageReplaceableProcessType,
    PackageReplacementProcess,
    PackageTriggerCandidate,
    PackageEffectQueueEntry,
    PackageEffectExecutionContext,
    PackageEffectContext,
    PackageTransientCardSet,
    PackageTargetSpec,
    PackageExactCardTargetSpec,
    PackageModifierLayer,
    PackageModifierOperation,
    PackageModifier,
    PackageContinuousEffectRecord,
    PackageContinuousEffect,
    PackageEngineError,
    PackageCustomHandler,
  ];
  const packageNameImportWitness: PackageNameImportWitness | null = null;

  expect(packageNameImportWitness).toBeNull();
});

test("TYP-001H relative runtime import/object-key smoke proof is not sufficient by itself", async () => {
  const relativeModule = await import("./index.js");
  expect(Object.keys(relativeModule)).toEqual([]);
  expect(Object.keys(EXPORT_OWNERSHIP_MANIFEST).length).toBeGreaterThan(
    Object.keys(relativeModule).length,
  );
});

test("ENG-012A match manifest export includes effect definition registry shape", () => {
  type EffectDefinitionRegistry = PackageMatchCardManifest["effectDefinitions"];
  const registry: EffectDefinitionRegistry = {};

  expect(registry).toEqual({});
});
