import { expect, test } from "vitest";
import { EXPORT_OWNERSHIP_MANIFEST } from "./export-ownership.manifest.js";

const canonicalModuleFiles = [
  "types/primitives.ts",
  "types/card-metadata.ts",
  "types/events.ts",
  "types/view.ts",
  "types/game-state.ts",
  "types/effects.ts",
  "types/decisions.ts",
  "types/runtime.ts",
];

async function readCanonicalModuleSources(): Promise<string[]> {
  const { readFile } = await import("node:fs/promises");

  return Promise.all(
    canonicalModuleFiles.map((fileName) =>
      readFile(new URL(`../../../contracts/${fileName}`, import.meta.url), {
        encoding: "utf8",
      }),
    ),
  );
}

import type {
  Action as PackageAction,
  AtomicMutation as PackageAtomicMutation,
  Attribute as PackageAttribute,
  AuditEntry as PackageAuditEntry,
  BanlistRecord as PackageBanlistRecord,
  BaseDecision as PackageBaseDecision,
  BattleState as PackageBattleState,
  BattleStep as PackageBattleStep,
  Brand as PackageBrand,
  CardCategory as PackageCardCategory,
  CardColor as PackageCardColor,
  CardFilter as PackageCardFilter,
  CardId as PackageCardId,
  CardImplementationRecord as PackageCardImplementationRecord,
  CardInstance as PackageCardInstance,
  CardMetadata as PackageCardMetadata,
  CardRef as PackageCardRef,
  CardSelectionCandidate as PackageCardSelectionCandidate,
  CardSelectionRequest as PackageCardSelectionRequest,
  CardSnapshot as PackageCardSnapshot,
  CardSupportStatus as PackageCardSupportStatus,
  CardVariant as PackageCardVariant,
  CausalityRef as PackageCausalityRef,
  ChooseEffectOptionDecision as PackageChooseEffectOptionDecision,
  ChooseOptionalActivationDecision as PackageChooseOptionalActivationDecision,
  ChooseReplacementDecision as PackageChooseReplacementDecision,
  ChooseTriggerOrderDecision as PackageChooseTriggerOrderDecision,
  Comparator as PackageComparator,
  ComputedCardView as PackageComputedCardView,
  ComputedGameView as PackageComputedGameView,
  Condition as PackageCondition,
  ConfirmLifeTriggerDecision as PackageConfirmLifeTriggerDecision,
  ContinuousEffect as PackageContinuousEffect,
  ContinuousEffectRecord as PackageContinuousEffectRecord,
  Cost as PackageCost,
  CustomHandler as PackageCustomHandler,
  DecisionId as PackageDecisionId,
  DecisionResponse as PackageDecisionResponse,
  DeckValidationError as PackageDeckValidationError,
  DeckValidationResult as PackageDeckValidationResult,
  DeckValidationWarning as PackageDeckValidationWarning,
  DecklistEntry as PackageDecklistEntry,
  DeclareLoopCountDecision as PackageDeclareLoopCountDecision,
  DeferredTriggerBucket as PackageDeferredTriggerBucket,
  Duration as PackageDuration,
  Effect as PackageEffect,
  EffectBlock as PackageEffectBlock,
  EffectCategory as PackageEffectCategory,
  EffectContext as PackageEffectContext,
  EffectDefinition as PackageEffectDefinition,
  EffectDefinitionMetadata as PackageEffectDefinitionMetadata,
  EffectExecutionContext as PackageEffectExecutionContext,
  EffectId as PackageEffectId,
  EffectOption as PackageEffectOption,
  EffectQueueEntry as PackageEffectQueueEntry,
  EngineError as PackageEngineError,
  EngineEvent as PackageEngineEvent,
  EngineEventId as PackageEngineEventId,
  EngineEventType as PackageEngineEventType,
  EngineResult as PackageEngineResult,
  EngineStepResult as PackageEngineStepResult,
  EventVisibility as PackageEventVisibility,
  FailurePolicy as PackageFailurePolicy,
  GameState as PackageGameState,
  InstanceId as PackageInstanceId,
  Keyword as PackageKeyword,
  LegalAction as PackageLegalAction,
  LifeCard as PackageLifeCard,
  Loadout as PackageLoadout,
  LoadoutId as PackageLoadoutId,
  LoopSignature as PackageLoopSignature,
  MatchCardManifest as PackageMatchCardManifest,
  MatchId as PackageMatchId,
  MatchSource as PackageMatchSource,
  MatchStatus as PackageMatchStatus,
  Modifier as PackageModifier,
  ModifierLayer as PackageModifierLayer,
  ModifierOperation as PackageModifierOperation,
  MulliganDecision as PackageMulliganDecision,
  NormalizedErrata as PackageNormalizedErrata,
  OncePerTurnRecord as PackageOncePerTurnRecord,
  OrderCardsDecision as PackageOrderCardsDecision,
  PaymentOption as PackagePaymentOption,
  PaymentSpec as PackagePaymentSpec,
  PayCostDecision as PackagePayCostDecision,
  PendingDecision as PackagePendingDecision,
  PlayerGameTimer as PackagePlayerGameTimer,
  PlayerId as PackagePlayerId,
  PlayerRef as PackagePlayerRef,
  PlayerState as PackagePlayerState,
  PoneglyphCardDetail as PackagePoneglyphCardDetail,
  PoneglyphErrata as PackagePoneglyphErrata,
  PoneglyphLegalityRecord as PackagePoneglyphLegalityRecord,
  PoneglyphOfficialFaq as PackagePoneglyphOfficialFaq,
  PoneglyphVariant as PackagePoneglyphVariant,
  Protection as PackageProtection,
  OpponentVisibleState as PackageOpponentVisibleState,
  PlayerView as PackagePlayerView,
  PublicBattleState as PackagePublicBattleState,
  PublicCardView as PackagePublicCardView,
  PublicDecision as PackagePublicDecision,
  PublicLegalAction as PackagePublicLegalAction,
  PublicLifeView as PackagePublicLifeView,
  PublicRevealRecord as PackagePublicRevealRecord,
  PublicTimerState as PackagePublicTimerState,
  PublicTurnState as PackagePublicTurnState,
  QueueEntryId as PackageQueueEntryId,
  ReplaceableProcessType as PackageReplaceableProcessType,
  ReplacementProcess as PackageReplacementProcess,
  ReplacementProcessState as PackageReplacementProcessState,
  ReplacementTrigger as PackageReplacementTrigger,
  ResolvedCard as PackageResolvedCard,
  ResolvedCardOverlay as PackageResolvedCardOverlay,
  ResolvedCardVariant as PackageResolvedCardVariant,
  ResolvedDeckCard as PackageResolvedDeckCard,
  RevealRecord as PackageRevealRecord,
  RestrictionIndex as PackageRestrictionIndex,
  RngDrawResult as PackageRngDrawResult,
  RngState as PackageRngState,
  RollbackConsentDecision as PackageRollbackConsentDecision,
  RulingNote as PackageRulingNote,
  RuntimeVersionSet as PackageRuntimeVersionSet,
  SearchRequest as PackageSearchRequest,
  SelectCardsDecision as PackageSelectCardsDecision,
  SelectionId as PackageSelectionId,
  SelectionSetId as PackageSelectionSetId,
  SelectTargetsDecision as PackageSelectTargetsDecision,
  SequencedEffect as PackageSequencedEffect,
  SourcePresencePolicy as PackageSourcePresencePolicy,
  StateHashInput as PackageStateHashInput,
  StateSeq as PackageStateSeq,
  SpectatorEvent as PackageSpectatorEvent,
  SpectatorPolicy as PackageSpectatorPolicy,
  SpectatorRevealRecord as PackageSpectatorRevealRecord,
  SpectatorView as PackageSpectatorView,
  SpectatorVisiblePlayerState as PackageSpectatorVisiblePlayerState,
  Target as PackageTarget,
  TargetCandidate as PackageTargetCandidate,
  TargetRequest as PackageTargetRequest,
  TargetSpec as PackageTargetSpec,
  TimerState as PackageTimerState,
  TimingWindowId as PackageTimingWindowId,
  TransientCardSet as PackageTransientCardSet,
  Trigger as PackageTrigger,
  TriggerCandidate as PackageTriggerCandidate,
  TurnState as PackageTurnState,
  VariantKey as PackageVariantKey,
  Visibility as PackageVisibility,
  VisiblePlayerState as PackageVisiblePlayerState,
  Winner as PackageWinner,
  Zone as PackageZone,
  ZoneRef as PackageZoneRef,
} from "@optcg/types";

test("TYP-001H ownership manifest keys exactly match canonical export type/interface names", async () => {
  const canonicalSource = (await readCanonicalModuleSources()).join("\n");

  const canonicalNames = [
    ...canonicalSource.matchAll(
      /export\s+(?:type|interface)\s+([A-Za-z0-9_]+)/g,
    ),
  ]
    .map((match) => match[1])
    .sort();
  const manifestNames = Object.keys(EXPORT_OWNERSHIP_MANIFEST).sort();

  expect(manifestNames).toEqual(canonicalNames);
});

test("TYP-001H every manifest-covered canonical export has exactly one valid owner", () => {
  const validOwners = new Set([
    "TYP-001A",
    "TYP-001B",
    "TYP-001C",
    "TYP-001D",
    "TYP-001E",
    "TYP-001F",
    "TYP-001G",
    "TYP-002A",
  ]);
  for (const owner of Object.values(EXPORT_OWNERSHIP_MANIFEST)) {
    expect(validOwners.has(owner)).toBe(true);
  }
});

test("TYP-001H manifest-covered exports resolve through package-name type imports", () => {
  type PackageNameImportWitness = [
    PackageBrand<string, "PackageNameImportWitness">,
    PackageCardId,
    PackageVariantKey,
    PackageLoadoutId,
    PackageInstanceId,
    PackagePlayerId,
    PackageMatchId,
    PackageEffectId,
    PackageDecisionId,
    PackageEngineEventId,
    PackageQueueEntryId,
    PackageTimingWindowId,
    PackageSelectionSetId,
    PackageSelectionId,
    PackageStateSeq,
    PackageCardCategory,
    PackageCardColor,
    PackageAttribute,
    PackageKeyword,
    PackageZone,
    PackageVisibility,
    PackageComparator,
    PackagePlayerRef,
    PackageBattleStep,
    PackageMatchSource,
    PackageZoneRef,
    PackageCardRef,
    PackageCardSnapshot,
    PackageCardVariant,
    PackageCardMetadata,
    PackageRuntimeVersionSet,
    PackageRulingNote,
    PackageCardSupportStatus,
    PackageCardImplementationRecord,
    PackageBanlistRecord,
    PackageResolvedCardOverlay,
    PackagePoneglyphLegalityRecord,
    PackagePoneglyphOfficialFaq,
    PackagePoneglyphErrata,
    PackagePoneglyphVariant,
    PackagePoneglyphCardDetail,
    PackageNormalizedErrata,
    PackageResolvedCardVariant,
    PackageResolvedCard,
    PackageMatchCardManifest,
    PackageDecklistEntry,
    PackageResolvedDeckCard,
    PackageDeckValidationError,
    PackageDeckValidationWarning,
    PackageDeckValidationResult,
    PackageLoadout,
    PackageEventVisibility,
    PackageEngineEvent,
    PackageEngineEventType,
    PackageCausalityRef,
    PackagePlayerGameTimer,
    PackageTimerState,
    PackagePublicTimerState,
    PackageRngState,
    PackageRngDrawResult<PackageCardRef>,
    PackageCardInstance,
    PackageLifeCard,
    PackagePlayerState,
    PackageWinner,
    PackageMatchStatus,
    PackageBattleState,
    PackageTurnState,
    PackageTargetCandidate,
    PackageCardSelectionCandidate,
    PackageAuditEntry,
    PackageLoopSignature,
    PackageRevealRecord,
    PackageReplacementProcessState,
    PackageDeferredTriggerBucket,
    PackageProtection,
    PackageOpponentVisibleState,
    PackagePlayerView,
    PackagePublicBattleState,
    PackagePublicCardView,
    PackagePublicDecision,
    PackagePublicLegalAction,
    PackagePublicLifeView,
    PackagePublicRevealRecord,
    PackageSpectatorRevealRecord,
    PackageSpectatorEvent,
    PackageRestrictionIndex,
    PackageComputedCardView,
    PackageComputedGameView,
    PackageEngineStepResult,
    PackageEngineResult,
    PackageStateHashInput,
    PackageAtomicMutation,
    PackageGameState,
    PackagePublicTurnState,
    PackageSpectatorPolicy,
    PackageSpectatorView,
    PackageSpectatorVisiblePlayerState,
    PackageVisiblePlayerState,
    PackageFailurePolicy,
    PackageSourcePresencePolicy,
    PackageEffectCategory,
    PackageTrigger,
    PackageCondition,
    PackageCost,
    PackageTargetRequest,
    PackageCardSelectionRequest,
    PackageTarget,
    PackageCardFilter,
    PackageDuration,
    PackageSearchRequest,
    PackageReplacementTrigger,
    PackageEffectOption,
    PackageSequencedEffect,
    PackageEffect,
    PackageEffectDefinitionMetadata,
    PackageEffectBlock,
    PackageEffectDefinition,
    PackagePaymentSpec,
    PackagePaymentOption,
    PackageDecisionResponse,
    PackageBaseDecision,
    PackageChooseTriggerOrderDecision,
    PackageChooseOptionalActivationDecision,
    PackagePayCostDecision,
    PackageSelectTargetsDecision,
    PackageSelectCardsDecision,
    PackageChooseEffectOptionDecision,
    PackageConfirmLifeTriggerDecision,
    PackageOrderCardsDecision,
    PackageMulliganDecision,
    PackageDeclareLoopCountDecision,
    PackageRollbackConsentDecision,
    PackageChooseReplacementDecision,
    PackagePendingDecision,
    PackageAction,
    PackageLegalAction,
    PackageOncePerTurnRecord,
    PackageReplaceableProcessType,
    PackageReplacementProcess,
    PackageTriggerCandidate,
    PackageEffectQueueEntry,
    PackageEffectExecutionContext,
    PackageEffectContext,
    PackageTransientCardSet,
    PackageTargetSpec,
    PackageModifierLayer,
    PackageModifierOperation,
    PackageModifier,
    PackageContinuousEffectRecord,
    PackageContinuousEffect,
    PackageEngineError,
    PackageCustomHandler,
  ];
  const packageNameImportWitness: PackageNameImportWitness | null = null;

  expect(packageNameImportWitness).toBeNull();
});

test("TYP-001H relative runtime import/object-key smoke proof is not sufficient by itself", async () => {
  const relativeModule = await import("./index.js");
  expect(Object.keys(relativeModule)).toEqual([]);
  expect(Object.keys(EXPORT_OWNERSHIP_MANIFEST).length).toBeGreaterThan(
    Object.keys(relativeModule).length,
  );
});

test("ENG-012A match manifest export includes effect definition registry shape", () => {
  type EffectDefinitionRegistry = PackageMatchCardManifest["effectDefinitions"];
  const registry: EffectDefinitionRegistry = {};

  expect(registry).toEqual({});
});
