export const TYP_001_STORY_OWNERS = [
  "TYP-001A",
  "TYP-001B",
  "TYP-001C",
  "TYP-001D",
  "TYP-001E",
  "TYP-001F",
  "TYP-001G",
  "TYP-002A",
  "TYP-007A",
  "TYP-007B",
  "TYP-007D",
  "TYP-008A",
  "TYP-009A",
  "TYP-009B",
  "TYP-010",
  "TYP-012A",
  "TYP-012B",
  "SUP-003A",
  "SUP-003I",
] as const;

export type Typ001StoryOwner = (typeof TYP_001_STORY_OWNERS)[number];

export const EXPORT_OWNERSHIP_MANIFEST = {
  Brand: "TYP-001A",
  CardId: "TYP-001A",
  VariantKey: "TYP-001A",
  LoadoutId: "TYP-001A",
  InstanceId: "TYP-001A",
  PlayerId: "TYP-001A",
  MatchId: "TYP-001A",
  EffectId: "TYP-001A",
  DecisionId: "TYP-001A",
  EngineEventId: "TYP-001A",
  QueueEntryId: "TYP-001A",
  TimingWindowId: "TYP-001A",
  SelectionSetId: "TYP-001A",
  SelectionId: "TYP-001A",
  StateSeq: "TYP-001A",
  CardCategory: "TYP-001B",
  CardColor: "TYP-001B",
  Attribute: "TYP-001B",
  Keyword: "TYP-001B",
  Zone: "TYP-001A",
  Visibility: "TYP-001A",
  Comparator: "TYP-001A",
  PlayerRef: "TYP-001A",
  BattleStep: "TYP-001A",
  MatchSource: "TYP-001B",
  ZoneRef: "TYP-001B",
  CardRef: "TYP-001B",
  CardSnapshot: "TYP-001B",
  CardVariant: "TYP-001B",
  CardMetadata: "TYP-001B",
  RuntimeVersionSet: "TYP-001B",
  RulingNote: "TYP-001B",
  CardSupportStatus: "TYP-001B",
  CardImplementationRecord: "TYP-001B",
  BanlistRecord: "TYP-001B",
  ResolvedCardOverlay: "TYP-001B",
  PoneglyphLegalityRecord: "TYP-001B",
  PoneglyphOfficialFaq: "TYP-001B",
  PoneglyphErrata: "TYP-001B",
  PoneglyphVariant: "TYP-001B",
  PoneglyphCardDetail: "TYP-001B",
  NormalizedErrata: "TYP-001B",
  ResolvedCardVariant: "TYP-001B",
  ResolvedCard: "TYP-001B",
  MatchCardManifest: "TYP-001B",
  DecklistEntry: "TYP-001B",
  ResolvedDeckCard: "TYP-001B",
  DeckValidationError: "TYP-001B",
  DeckValidationWarning: "TYP-001B",
  DeckValidationResult: "TYP-001B",
  Loadout: "TYP-001B",
  EventVisibility: "TYP-001C",
  EngineEvent: "TYP-001C",
  EngineEventType: "TYP-001C",
  CausalityRef: "TYP-001C",
  PlayerGameTimer: "TYP-001F",
  TimerState: "TYP-001F",
  PublicTimerState: "TYP-001F",
  SequenceSegmentResultMap: "TYP-007B",
  SequenceSavedResultReferenceMap: "TYP-007B",
  EffectExecutionPendingDecisionContinuation: "TYP-008A",
  EffectExecutionFrame: "TYP-008A",
  SpectatorPolicy: "TYP-002A",
  PublicTurnState: "TYP-002A",
  PublicBattleState: "TYP-002A",
  PublicCardView: "TYP-002A",
  PublicLifeView: "TYP-002A",
  VisiblePlayerState: "TYP-002A",
  OpponentVisibleState: "TYP-002A",
  SpectatorVisiblePlayerState: "TYP-002A",
  PublicDecision: "TYP-002A",
  PublicChooseQuantityDecision: "TYP-007A",
  PublicChooseTriggerOrderDecision: "TYP-007A",
  PublicSelectCardsDecision: "TYP-007A",
  PublicSelectTargetsDecision: "TYP-007A",
  PublicOrderCardsDecision: "TYP-007A",
  PublicPendingDecision: "TYP-007A",
  PublicLegalAction: "TYP-002A",
  PublicRevealRecord: "TYP-002A",
  SpectatorRevealRecord: "TYP-002A",
  SpectatorEvent: "TYP-002A",
  PlayerView: "TYP-002A",
  SpectatorView: "TYP-002A",
  RngState: "TYP-001F",
  RngDrawResult: "TYP-001F",
  CardInstance: "TYP-001F",
  LifeCard: "TYP-001F",
  PlayerState: "TYP-001F",
  Winner: "TYP-001F",
  MatchStatus: "TYP-001F",
  BattleState: "TYP-001F",
  TurnState: "TYP-001F",
  SetupContinuationState: "SUP-003I",
  TargetCandidate: "TYP-001E",
  CardSelectionCandidate: "TYP-001E",
  AuditEntry: "TYP-001F",
  LoopSignature: "TYP-001F",
  RevealRecord: "TYP-001F",
  ReplacementProcessState: "TYP-001F",
  DeferredTriggerBucket: "TYP-001F",
  ProtectionFieldRemovalProcessFamily: "TYP-012A",
  ProtectionFieldRemovalClassification: "TYP-012A",
  ProtectionFieldRemovalSourceKind: "TYP-012A",
  ProtectionFieldRemovalSourceControllerRelation: "TYP-012A",
  ProtectionFieldRemovalTargetScope: "TYP-012A",
  ProtectionExclusionPolicy: "TYP-012A",
  ProtectionFieldRemovalExclusions: "TYP-012A",
  ProtectionFieldRemovalMetadata: "TYP-012A",
  SimpleProtection: "TYP-012A",
  FieldRemovalProtection: "TYP-012A",
  Protection: "TYP-001F",
  RestrictionIndex: "TYP-001F",
  ComputedCardView: "TYP-001F",
  ComputedGameView: "TYP-001F",
  EngineStepResult: "TYP-001G",
  EngineResult: "TYP-001G",
  StateHashInput: "TYP-001G",
  AtomicMutation: "TYP-001G",
  GameState: "TYP-001G",
  FailurePolicy: "TYP-001D",
  SourcePresencePolicy: "TYP-001D",
  EffectCategory: "TYP-001D",
  Trigger: "TYP-001D",
  OpponentActivationKind: "TYP-001D",
  Condition: "TYP-001D",
  Cost: "TYP-001D",
  OptionalTrashFromHandCost: "SUP-003A",
  OptionalMoveCardsCost: "TYP-001D",
  ScopedOptionalFieldTrashCostFilter: "SUP-003A",
  ScopedOptionalFieldTrashCost: "SUP-003A",
  OptionalChooseOneTrashCostAlternative: "SUP-003A",
  OptionalChooseOneTrashCost: "SUP-003A",
  OptionalCost: "TYP-009A",
  EffectBlockCost: "SUP-003A",
  TargetRequest: "TYP-001D",
  MultiZoneTargetRequest: "TYP-001D",
  SelectedTargetsRequest: "TYP-010",
  TargetPlayerRef: "TYP-001D",
  ExactCardinality: "TYP-007A",
  UpToCardinality: "TYP-007A",
  Cardinality: "TYP-007A",
  CardSelectionRequest: "TYP-001D",
  DynamicNumberValue: "TYP-001D",
  Target: "TYP-001D",
  CardFilter: "TYP-001D",
  Duration: "TYP-001D",
  SearchRequest: "TYP-001D",
  SequenceSegmentResult: "TYP-007B",
  OptionalCostSegmentResult: "TYP-009A",
  SavedFieldObjectReferenceFamily: "TYP-009B",
  SavedFieldObjectTargetBinding: "TYP-009B",
  SavedFieldObjectReference: "TYP-009B",
  SavedFieldObjectReferenceFailureReason: "TYP-009B",
  SavedFieldObjectReferenceFailure: "TYP-009B",
  SavedFieldObjectZone: "TYP-009B",
  SavedFieldObjectTarget: "TYP-009B",
  SavedSelectedCardsReference: "TYP-007B",
  SavedSelectedTargetsReference: "TYP-009B",
  SavedPaidCostReference: "TYP-007B",
  SavedProducedObjectsReference: "TYP-009B",
  SequenceSavedResultReference: "TYP-007B",
  HandSelectionId: "TYP-007D",
  SelectCardsEffect: "TYP-007D",
  SelectTargetsEffect: "TYP-010",
  SelectTargetsProducerSegment: "TYP-010",
  HandSelectCardsEffect: "TYP-007D",
  PlaySelectedEffect: "TYP-007D",
  PlayHandSelectedEffect: "TYP-007D",
  PlaySourceEffect: "TYP-007D",
  PayCostEffect: "TYP-009A",
  EffectDslFieldRemovalProtection: "TYP-012B",
  ReplacementTrigger: "TYP-001D",
  EffectOption: "TYP-001D",
  SequencedEffect: "TYP-001D",
  Effect: "TYP-001D",
  EffectDefinitionMetadata: "TYP-001D",
  EffectBlock: "TYP-001D",
  EffectDefinition: "TYP-001D",
  PaymentSpec: "TYP-001E",
  PaymentOption: "TYP-001E",
  PaymentResponse: "TYP-009A",
  PaymentDeclinedResponse: "TYP-009A",
  DecisionResponse: "TYP-001E",
  BaseDecision: "TYP-001E",
  ChooseTriggerOrderDecision: "TYP-001E",
  ChooseOptionalActivationDecision: "TYP-001E",
  PayCostDecision: "TYP-001E",
  OptionalPayCostDecision: "TYP-009A",
  SelectTargetsDecision: "TYP-001E",
  SelectCardsDecision: "TYP-001E",
  ChooseEffectOptionDecision: "TYP-001E",
  ConfirmLifeTriggerDecision: "TYP-001E",
  OrderCardsDecision: "TYP-001E",
  MulliganDecision: "TYP-001E",
  DeclareLoopCountDecision: "TYP-001E",
  RollbackConsentDecision: "TYP-001E",
  ChooseReplacementDecision: "TYP-001E",
  ChooseQuantityResponse: "TYP-007A",
  ChooseQuantityDecision: "TYP-007A",
  ExactQuantityDecision: "TYP-007A",
  PendingDecision: "TYP-001E",
  Action: "TYP-001E",
  LegalAction: "TYP-001E",
  OncePerTurnRecord: "TYP-001F",
  ReplaceableProcessType: "TYP-001F",
  ReplacementProcess: "TYP-001F",
  TriggerCandidate: "TYP-001F",
  EffectQueueEntry: "TYP-001F",
  EffectExecutionContext: "TYP-001F",
  EffectContext: "TYP-001F",
  TransientCardSet: "TYP-001F",
  TargetSpec: "TYP-001F",
  ExactCardTargetSpec: "TYP-009B",
  ModifierLayer: "TYP-001F",
  ModifierOperation: "TYP-001F",
  Modifier: "TYP-001F",
  ContinuousEffectRecord: "TYP-001F",
  ContinuousEffect: "TYP-001F",
  EngineError: "TYP-001G",
  CustomHandler: "TYP-001G",
} as const satisfies Record<string, Typ001StoryOwner>;
