import {
  parseActiveCharacterPredicate,
  parseCharacterCategoryPredicate,
  parseColorPredicate,
  parseEventCategoryPredicate,
  parseGenericCardPredicate,
  parseRestedCharacterPredicate,
  parseStageCategoryPredicate,
} from "./category.js";
import {
  parseEffectEntryPointPredicate,
  parseEffectEntryPointPresencePredicate,
} from "./effect-entry.js";
import {
  parseCardNameContainsPredicate,
  parseDifferentNamesPredicate,
  parseNameCardPredicate,
  parseNameExclusionPredicate,
  parseNamePredicate,
  parseSelfExclusionPredicate,
} from "./name.js";
import {
  parseAttachedDonPredicate,
  parseCostPredicate,
  parseDynamicDonFieldCostPredicate,
  parsePowerPredicate,
} from "./stats.js";
import {
  parseAttributeCardPredicate,
  parseAttributeCategoryPredicate,
  parseAttributeOnlyPredicate,
  parseGenericTypeCardPredicate,
  parseMultiTypePredicate,
  parseMultiTypeCardPredicate,
  parseMultiTypeCategoryPredicate,
  parseMultiTypeLeaderOrCharacterPredicate,
  parseQuotedTypeIncludingPredicate,
  parseTypeCharacterPredicate,
  parseTypeLeaderOrCharacterPredicate,
  parseTypeLeaderOrStagePredicate,
  parseTypeOnlyPredicate,
  parseTypeOrAttributePredicate,
  parseTypeOrAttributeCategoryPredicate,
} from "./type-attribute.js";
import type { PredicateParser } from "./types.js";

export const predicateParsers: readonly PredicateParser[] = [
  parseColorPredicate,
  parseMultiTypeCategoryPredicate,
  parseMultiTypeLeaderOrCharacterPredicate,
  parseMultiTypeCardPredicate,
  parseTypeOrAttributeCategoryPredicate,
  parseTypeOrAttributePredicate,
  parseTypeLeaderOrCharacterPredicate,
  parseTypeLeaderOrStagePredicate,
  parseTypeCharacterPredicate,
  parseGenericTypeCardPredicate,
  parseMultiTypePredicate,
  parseQuotedTypeIncludingPredicate,
  parseTypeOnlyPredicate,
  parseAttributeCardPredicate,
  parseAttributeCategoryPredicate,
  parseAttributeOnlyPredicate,
  parseActiveCharacterPredicate,
  parseRestedCharacterPredicate,
  parseEventCategoryPredicate,
  parseStageCategoryPredicate,
  parseCharacterCategoryPredicate,
  parseGenericCardPredicate,
  parsePowerPredicate,
  parseAttachedDonPredicate,
  parseEffectEntryPointPresencePredicate,
  parseEffectEntryPointPredicate,
  parseDynamicDonFieldCostPredicate,
  parseCostPredicate,
  parseCardNameContainsPredicate,
  parseSelfExclusionPredicate,
  parseNameExclusionPredicate,
  parseNameCardPredicate,
  parseNamePredicate,
  parseDifferentNamesPredicate,
];
